### ISSUE TITLE
Not tracking correctly

### ISSUE THREAD

**Issue by rjmessing** [Debuggernaut/LucidNightmareHelper#12]
I'm currently doing the Lucid Nightmare maze and the tracking is wrong.  I went into my room 24 and its connected to room 20....it popped me below room 20 and created a 25th room.

I know this is old content and all and you'll probably not fix this addon.

I'm glad this addon is working for 10.0.7 even if buggy

**Comment by Debuggernaut** [comment]
oh, sorry to hear that.. I dunno if I can fix it any time soon, since I'm working full time and trying to work full time on some side-stuff too, and of course there's full-time dadhood as well, haha

There's this site you can use too that might help out: https://nightswimmer.github.io/EndlessHalls

you can use the addon and the site together, the addon's export feature is compatible with the site's import feature.  So you basically can export your routes, then pick through them to figure out where the teleport trap was

**Comment by rjmessing** [comment]
After running the maze for a while I think the issue was that I was unfamiliar with the program.  It seemed to map just fine, though there were some bugs that ended up putting me where I wasn't. 

I'm a dad too so I know how it goes.

**Comment by Debuggernaut** [comment]
Glad to hear it worked out!  Yeah, sorry the map is so janky, I need to get
in there and fix it one of these days..
